# Generated by Django 6.0.2 on 2026-02-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_cropimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
