# Generated by Django 6.0.2 on 2026-02-21 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_alter_upload_owner_alter_upload_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['owner'], name='uploads_upl_owner_i_808ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['status'], name='uploads_upl_status_824016_idx'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['created_at'], name='uploads_upl_created_872b24_idx'),
        ),
    ]
