# Generated by Django 6.0.2 on 2026-02-21 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['owner'], name='marketplace_owner_i_8cfc3c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='marketplace_status_bcb480_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='marketplace_created_1f132e_idx'),
        ),
    ]
